apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: springboot-grpc-service
  description: Template for generating a Spring Boot gRPC microservice
spec:
  type: service
  path: templates/springboot-grpc-service
  owner: your-team@example.com
  schema:
    properties:
      groupId:
        type: string
        title: Group ID
        default: com.example
      artifactId:
        type: string
        title: Artifact ID
      version:
        type: string
        title: Version
        default: 0.0.1-SNAPSHOT
      javaPackage:
        type: string
        title: Java Package
        default: com.example.grpc
      description:
        type: string
        title: Description
        default: A Spring Boot gRPC microservice

  operations:
    - id: generate
      description: Generate a Spring Boot gRPC microservice
      steps:
        - id: create-project
          name: Create Spring Boot gRPC project
          action: exec
          input:
            command: curl https://start.spring.io/starter.zip -o app.zip && unzip -q app.zip -d $WORKSPACE && mv $WORKSPACE/*/* $WORKSPACE/
          conditions: []

  template:
    type: static
