apiVersion: backstage.io/v1
kind: Template
metadata:
  name: simple-spring-boot-app
  description: Template for generating a simple Spring Boot application
spec:
  type: service
  path: templates/simple-spring-boot-app
  owner: adrian.parez.gomez@example.com
  schema:
    properties:
      groupId:
        type: string
        title: Group ID
        default: com.example
      artifactId:
        type: string
        title: Artifact ID
      version:
        type: string
        title: Version
        default: 0.0.1-SNAPSHOT

  operations:
    - id: generate
      description: Generate a simple Spring Boot application
      steps:
        - id: create-project
          name: Create Spring Boot project
          action: exec
          input:
            command: curl https://start.spring.io/starter.zip -o app.zip && unzip -q app.zip -d $WORKSPACE && mv $WORKSPACE/*/* $WORKSPACE/
          conditions: []

  template:
    type: static
